# Серверы http и https. Сам сайт описан в bitrix.inc.
# https-сервер и редирект с http создаёт ./bitrix-https.sh (файлы в docker/nginx/https/).
include /etc/nginx/https.d/server*.conf;

server {
    listen 80;
    server_name _;

    include /etc/nginx/https.d/redirect*.conf;
    include /etc/nginx/bitrix.inc;
}
